name: trabalho
channels:
  - conda-forge
  - defaults
dependencies:
  - python>3.6
  - notebook>5.2
  - jupyter_dashboards
  - jupyter_dashboards_bundlers
  - matplotlib
  - sympy
  - numpy
  - ipywidgets=7
  - jupyter_latex_envs
  - latexcodec
